version: '3.8'
services:
  db-service:
    image: postgres:14
    container_name: database-server
    environment:
      POSTGRES_DB: expensetracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-manager:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@expensetracker.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db-service

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-service:5432/expensetracker
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - db-service

networks:
  default:
    name: db-network
    external: true

volumes:
  pgdata:
