version: '3.8'
services:
  # Database service (Postgres)
  db-service:
    image: postgres:14
    container_name: database-server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Database manager (PgAdmin)
  db-manager:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWD}
    ports:
      - "5050:80"
    depends_on:
      - db-service

  # Expense Tracker container
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-service:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWD}
    ports:
      - "8080:8080"
    depends_on:
      - db-service

networks:
  default:
    name: db-network
    external: true

volumes:
  pgdata: